# -*- coding: utf-8 -*-
"""HW11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-36GiDJdjFjGh2s2RwivdgLZkprOstU
"""

import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

with open("botsv1.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)
print("Строк:", len(df), "Колонок:", len(df.columns))

dest_col = "result.dest"
event_col = "result.EventCode"

print("dest_col есть:", dest_col in df.columns)
print("event_col есть:", event_col in df.columns)

def to_scalar(x):
    if isinstance(x, list) and len(x) > 0:
        return x[0]
    return x

def clean_series(s):
    s = s.apply(to_scalar)
    s = s.astype(str).fillna("").str.strip()
    s = s[(s != "") & (s.str.lower() != "none") & (s.str.lower() != "nan")]
    return s

dest_s = clean_series(df[dest_col])
event_s = clean_series(df[event_col])

event_s = event_s[event_s.str.upper() != "DNS"]

def plot_top10(series, title, xlabel):
    top = series.value_counts().head(10)
    plt.figure(figsize=(14, 6))
    sns.barplot(x=top.index, y=top.values)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Количество запросов")
    plt.xticks(rotation=60, ha="right")
    plt.tight_layout()
    plt.show()
    display(top.to_frame("count"))

plot_top10(dest_s, "Топ-10 DNS-адресов/домены (поле dest)", "Адрес/домен")
plot_top10(event_s, "Топ-10 EventCode (EventID) WinEventLog", "EventCode")
