# -*- coding: utf-8 -*-
"""Data_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpF_jfrTVmHERWJtg_k0KYun2ZAZHsp3
"""

import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# загрузка данных из файла
with open("events.json", "r") as f:
    data = json.load(f)

# преобразование в DataFrame
df = pd.DataFrame(data["events"])

# визуализация
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x="signature")
plt.title("Распределение типов событий безопасности")
plt.xticks(rotation=90)
plt.show()